### ISSUE TITLE
sort parameter not working on inbox_controller#get_emails

### ISSUE THREAD

**Issue by DGaffney** [mailslurp/mailslurp-client-ruby#2]
Hello - I'm a brand new paying customer and I'm not able to sort emails by the sort parameter as outlined in inbox_controller#get_emails - running this code right now:

```
inbox_controller.get_emails(inbox.id, sort: "ASC")
inbox_controller.get_emails(inbox.id, sort: "DESC")
```
Both result in identically-ordered emails, which should obviously not be the case. Please fix or let me know what I'm doing wrong!

**Comment by jackmahoney** [comment]
Thanks for pointing this out - it could be a problem in the ruby library or in the API. I will open a ticket for this now to investigate. I'll keep this issue open for now and post an update in a few days. Thanks for your patience. Try the pagination endpoints, get_all_emails for instance in the meantime.

**Comment by jackmahoney** [comment]
So @DGaffney I confirm that the email controller sort endpoints work as expect - but that the inbox controller get email method is complicated. It is an older method and accepts retry and wait options.  An easier way to get emails is with the email_controller.get_emails_paginated method.

Please see https://www.mailslurp.com/docs/ruby/docs/EmailControllerApi/#get-emails-paginated

We will continue to investigate this particular bug though. Does that help for now?

**Comment by DGaffney** [comment]
Yep - thanks for the update @jackmahoney - I am not blocked by this right now but figured I should raise the issue as I saw it in the wild.

**Comment by jackmahoney** [comment]
Ok we have also found the bug in the API. Our database ORM was not sorting a field correctly for that method. We will push out a version of the API now that will fix the result for your client. Thanks for reporting the issue.

**Comment by jackmahoney** [comment]
This is now fixed in the latest release. Thanks
